version: '3.8'

services:
  realnet-admin:
    container_name: realnet-admin
    build:
      context: ./realnet-admin
      dockerfile: Dockerfile
    ports:
      - "8009:80"
    volumes:
      - ./realnet-admin:/var/www/html
      - /var/www/html/vendor
    env_file:
      - ./realnet-admin/.env
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    networks:
      - realnet-network

  # realnet-app:
  #   container_name: realnet-app
  #   build:
  #     context: ./realnet-app
  #     dockerfile: Dockerfile
  #   expose:
  #     - "3000"
  #   environment:
  #     - NODE_ENV=production
  #     - INTERNAL_API_URL=http://realnet-admin
  #     # Public URL for client-side fetches (must be provided at runtime or build time depending on usage)
  #     - NEXT_PUBLIC_API_BASE_URL=https://admin.realnet-web.co.za
  #   restart: always
  #   networks:
  #     - realnet-network

  mysql:
    image: mysql:8.0
    container_name: realnet_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: RealNet1
      MYSQL_DATABASE: realnet
    networks:
      - realnet-network

volumes:
  mysql_data:

networks:
  realnet-network:
    driver: bridge
