version: '3.8'

services:
  realnet-admin:
    container_name: realnet-admin
    image: realnet-admin
    build:
      context: ./realnet-admin
      dockerfile: Dockerfile
    expose:
      - "80"
    env_file:
      - ./realnet-admin/.env
    # environment:
    #   - APP_ENV=production
    #   - APP_DEBUG=false
    restart: always

  mysql:
    image: mysql:8.0
    container_name: realnet_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: RealNet1
      MYSQL_DATABASE: realnet
    restart: always

volumes:
  mysql_data:
